modified backend only 11:56

diff --git a/backend-pipeline.gocd.yaml b/backend-pipeline.gocd.yaml
--- a/backend-pipeline.gocd.yaml
+++ b/backend-pipeline.gocd.yaml
@@ -65,12 +65,12 @@ pipelines:
                          if ls "${BUILD_DIR}/ps_be_*.zip" > /dev/null 2>&1; then
                           echo "Found existing ps_be_*.zip files. Removing them..."
                           sudo rm -f "${BUILD_DIR}/ps_be_*.zip" || { echo "Failed to remove existing zip files"; exit 1; }
-
-                        echo "Changing permissions of BUILD_DIR to ubuntu:ubuntu..."             
-                          sudo chown -R ubuntu:ubuntu "${BUILD_DIR}" || { echo "Failed to change permissions of BUILD_DIR"; exit 1; }
                         else
                         echo "No existing ps_be_*.zip files found. Proceeding..."
                         fi
+
+                        echo "Changing permissions of BUILD_DIR to ubuntu:ubuntu..."             
+                          sudo chown -R ubuntu:ubuntu "${BUILD_DIR}" || { echo "Failed to change permissions of BUILD_DIR"; exit 1; }
 
                         echo "Accessing SFTP machine to fetch the backend zip file..."
                         sftp -o StrictHostKeyChecking=no -i /var/go/.ssh/id_rsa ${SFTP_USER}@${SFTP_HOST} <<EOF
