modified backend 18:03

diff --git a/backend-pipeline.gocd.yaml b/backend-pipeline.gocd.yaml
--- a/backend-pipeline.gocd.yaml
+++ b/backend-pipeline.gocd.yaml
@@ -34,7 +34,7 @@ pipelines:
                         export SERVICE=PrimeSquare.service
                         export DB_SCRIPTS_DIR=/home/ubuntu/prime-square/database-scripts
                         export DB_USER=psdbadmin
-                        export DB_PASS=6%EOm@Te1sb19Th6
+                        
                         export SFTP_HOST=192.168.56.106
                         export SFTP_USER=surya
                         export SFTP_KEY=/var/go/.ssh/id_rsa
@@ -110,6 +110,22 @@ pipelines:
                           echo "Service file already exists. Skipping copy."
                         fi
 
+                        echo "Fetching DB password securely..."
+                        DB_PASS=$(cat /var/go/secrets/db_pass)
+                        if [ -z "${DB_PASS}" ]; then
+                          echo "Database password is missing!"
+                          exit 1
+                        fi
+                        
+                        echo "Executing database scripts..."
+                        mysql < "${DB_SCRIPTS_DIR}/ddl_drop_schema_script.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ddl_drop_schema_script.sql"; exit 1; }
+                        mysql < "${DB_SCRIPTS_DIR}/idfc_primesquare_workflow_ddl_dml.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute primesquare_workflow_ddl_dml.sql"; exit 1; }
+                        mysql < "${DB_SCRIPTS_DIR}/ddl_create_scripts.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ddl_create_scripts.sql"; exit 1; }
+                        mysql < "${DB_SCRIPTS_DIR}/dml_insert_scripts.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute dml_insert_scripts.sql"; exit 1; }
+                        mysql < "${DB_SCRIPTS_DIR}/ps_index_create.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ps_index_create.sql"; exit 1; }
+
+
+                        
 
                         echo "Reloading systemd daemon..."
                         sudo systemctl daemon-reload || { echo "Failed to reload systemd daemon"; exit 1; }
