modified front-end at 11:55

diff --git a/backend-pipeline.gocd.yaml b/backend-pipeline.gocd.yaml
--- a/backend-pipeline.gocd.yaml
+++ b/backend-pipeline.gocd.yaml
@@ -117,11 +117,12 @@ pipelines:
                         echo "Reloading systemd daemon..."
                         sudo systemctl daemon-reload || { echo "Failed to reload systemd daemon"; exit 1; }
 
-                        echo "Giving execute permissions to database scripts..."
-                        sudo chmod -R +x "${DB_SCRIPTS_DIR}" || { echo "Failed to give execute permissions to database scripts"; exit 1; }
-                        sudo chown -R go:go "${DB_SCRIPTS_DIR}" || { echo "Failed to change ownership of DB_SCRIPTS_DIR"; exit 1; }
+                        echo "Setting permissions and ownership for database scripts..."
+                        sudo chmod 644 "${DB_SCRIPTS_DIR}"/*.sql || { echo "Failed to set permissions for database scripts"; exit 1; }
+                        sudo chown go:go "${DB_SCRIPTS_DIR}"/*.sql || { echo "Failed to change ownership of database scripts"; exit 1; }
 
                         echo "Executing database scripts..."
+                        sudo mysql < "${DB_SCRIPTS_DIR}/ddl_drop_schema_script.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ddl_drop_schema_script.sql"; exit 1; }
                         sudo mysql < "${DB_SCRIPTS_DIR}/idfc_primesquare_workflow_ddl_dml.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute primesquare_workflow_ddl_dml.sql"; exit 1; }
                         sudo mysql < "${DB_SCRIPTS_DIR}/ddl_create_scripts.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ddl_create_scripts.sql"; exit 1; }
                         sudo mysql < "${DB_SCRIPTS_DIR}/dml_insert_scripts.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute dml_insert_scripts.sql"; exit 1; }
