changed permissions

diff --git a/backend-pipeline.gocd.yaml b/backend-pipeline.gocd.yaml
--- a/backend-pipeline.gocd.yaml
+++ b/backend-pipeline.gocd.yaml
@@ -63,20 +63,20 @@ pipelines:
                           echo "${SERVICE} does not exist. Proceeding..."
                         fi
 
-                        echo "Checking for existing ps_be_*.zip files in BUILD_DIR..."
-                         if ls "${BUILD_DIR}/ps_be_*.zip" > /dev/null 2>&1; then
-                          echo "Found existing ps_be_*.zip files. Removing them..."
-                          sudo rm -f "${BUILD_DIR}/ps_be_*.zip" || { echo "Failed to remove existing zip files"; exit 1; }
-                        else
-                        echo "No existing ps_be_*.zip files found. Proceeding..."
-                        fi
-
                         echo "Checking and creating BUILD_DIR if needed..."
                         if [ ! -d "${BUILD_DIR}" ]; then
                           echo "BUILD_DIR does not exist. Creating ${BUILD_DIR}..."
                           mkdir -p "${BUILD_DIR}" || { echo "Failed to create ${BUILD_DIR}"; exit 1; }
                         else
                           echo "BUILD_DIR exists. Using existing ${BUILD_DIR}..."
+                        fi
+
+                        echo "Checking for existing ps_be_*.zip files in BUILD_DIR..."
+                         if ls "${BUILD_DIR}/ps_be_*.zip" > /dev/null 2>&1; then
+                          echo "Found existing ps_be_*.zip files. Removing them..."
+                          sudo rm -f "${BUILD_DIR}/ps_be_*.zip" || { echo "Failed to remove existing zip files"; exit 1; }
+                        else
+                        echo "No existing ps_be_*.zip files found. Proceeding..."
                         fi
 
                         echo "Accessing SFTP machine to fetch the backend zip file..."
@@ -111,8 +111,9 @@ pipelines:
                         echo "Listing extracted files in BE_TARGET_DIR..."
                         ls -l "${BE_TARGET_DIR}"
 
-                        echo "Changing permissions of BE_TARGET_DIR to ubuntu:ubuntu..."
+                        echo "Changing permissions of BE_TARGET_DIR and BUILD_DIR to ubuntu:ubuntu..."
                         sudo chown -R ubuntu:ubuntu "${BE_TARGET_DIR}" || { echo "Failed to change permissions of BE_TARGET_DIR"; exit 1; }
+                        sudo chown -R ubuntu:ubuntu "${BUILD_DIR}" || { echo "Failed to change permissions of BUILD_DIR"; exit 1; }
 
                         echo "Checking and copying service file if needed..."
                         if [ ! -f /etc/systemd/system/${SERVICE} ]; then
