modified front-end at 02:23

diff --git a/backend-pipeline.gocd.yaml b/backend-pipeline.gocd.yaml
--- a/backend-pipeline.gocd.yaml
+++ b/backend-pipeline.gocd.yaml
@@ -119,6 +119,7 @@ pipelines:
 
                         echo "Giving execute permissions to database scripts..."
                         sudo chmod -R +x "${DB_SCRIPTS_DIR}" || { echo "Failed to give execute permissions to database scripts"; exit 1; }
+                        sudo chown -R ubuntu:ubuntu "${DB_SCRIPTS_DIR}" || { echo "Failed to change ownership of DB_SCRIPTS_DIR"; exit 1; }
 
                         echo "Executing database scripts..."
                         sudo mysql < "${DB_SCRIPTS_DIR}/ddl_drop_schema_script.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ddl_drop_schema_script.sql"; exit 1; }
