removing zip files in build dir and added backend.zip

diff --git a/backend-pipeline.gocd.yaml b/backend-pipeline.gocd.yaml
--- a/backend-pipeline.gocd.yaml
+++ b/backend-pipeline.gocd.yaml
@@ -85,7 +85,7 @@ pipelines:
                         echo "Accessing SFTP machine to fetch the backend zip file..."
                         sftp -o StrictHostKeyChecking=no -i /var/go/.ssh/id_rsa ${SFTP_USER}@${SFTP_HOST} <<EOF
                         cd ${SFTP_UPLOADS_DIR}
-                        get ps_be_*.zip ${BUILD_DIR}/ps_be_*.zip
+                        get ps_be_*.zip ${BUILD_DIR}/backend.zip
                         bye
                         EOF
                         if [ $? -ne 0 ]; then
@@ -102,11 +102,11 @@ pipelines:
                         fi
 
                         echo "Copying and unzipping the backend artifacts to BE_TARGET_DIR..."
-                        sudo cp "${BUILD_DIR}/ps_be_*.zip" "${BE_TARGET_DIR}/" || { echo "Failed to copy zip file"; exit 1; }
-                        sudo unzip -o "${BE_TARGET_DIR}/ps_be_*.zip" -d "${BE_TARGET_DIR}" || { echo "Failed to unzip backend.zip"; exit 1; }
+                        sudo cp "${BUILD_DIR}/backend.zip" "${BE_TARGET_DIR}/" || { echo "Failed to copy zip file"; exit 1; }
+                        sudo unzip -o "${BE_TARGET_DIR}/backend.zip" -d "${BE_TARGET_DIR}" || { echo "Failed to unzip backend.zip"; exit 1; }
 
                         echo "Removing the zip file from BE_TARGET_DIR..."
-                        sudo rm -f "${BE_TARGET_DIR}/ps_be_*.zip"
+                        sudo rm -f "${BE_TARGET_DIR}/backend.zip"
 
                         echo "Listing extracted files in BE_TARGET_DIR..."
                         ls -l "${BE_TARGET_DIR}"
