modified backend only 12:03

diff --git a/backend-pipeline.gocd.yaml b/backend-pipeline.gocd.yaml
--- a/backend-pipeline.gocd.yaml
+++ b/backend-pipeline.gocd.yaml
@@ -60,6 +60,8 @@ pipelines:
                         else
                           echo "BUILD_DIR exists. Using existing ${BUILD_DIR}..."
                         fi
+                        sudo chmod -R 775 "${BUILD_DIR}" || { echo "Failed to set permissions for BUILD_DIR"; exit 1; }
+                        sudo chown -R ubuntu:ubuntu "${BUILD_DIR}" || { echo "Failed to change ownership of BUILD_DIR"; exit 1; }
 
                         echo "Checking for existing ps_be_*.zip files in BUILD_DIR..."
                          if ls "${BUILD_DIR}/ps_be_*.zip" > /dev/null 2>&1; then
@@ -68,9 +70,6 @@ pipelines:
                         else
                         echo "No existing ps_be_*.zip files found. Proceeding..."
                         fi
-
-                        echo "Changing permissions of BUILD_DIR to ubuntu:ubuntu..."             
-                          sudo chown -R ubuntu:ubuntu "${BUILD_DIR}" || { echo "Failed to change permissions of BUILD_DIR"; exit 1; }
 
                         echo "Accessing SFTP machine to fetch the backend zip file..."
                         sftp -o StrictHostKeyChecking=no -i /var/go/.ssh/id_rsa ${SFTP_USER}@${SFTP_HOST} <<EOF
