modified 17:43

diff --git a/backend-pipeline.gocd.yaml b/backend-pipeline.gocd.yaml
--- a/backend-pipeline.gocd.yaml
+++ b/backend-pipeline.gocd.yaml
@@ -48,8 +48,10 @@ pipelines:
                           echo "BUILD_DIR does not exist. Creating ${BUILD_DIR}..."
                           sudo mkdir -p "${BUILD_DIR}" || { echo "Failed to create ${BUILD_DIR}"; exit 1; }
                         fi
-                        sudo chmod -R 775 "${BUILD_DIR}" || { echo "Failed to set permissions for BUILD_DIR"; exit 1; }
-                        sudo chown -R ubuntu:ubuntu "${BUILD_DIR}" || { echo "Failed to change ownership of BUILD_DIR"; exit 1; }
+
+                        USER="$(whoami)" 
+                        echo "Current user is $USER"
+                        sudo chown -R "$USER:$USER" "${BUILD_DIR}" || { echo "Failed to change ownership of BUILD_DIR"; exit 1; }
 
                         echo "Checking if BE_TARGET_DIR exists..."
                         if [ -d "${BE_TARGET_DIR}" ]; then
@@ -59,8 +61,10 @@ pipelines:
                           echo "BE_TARGET_DIR does not exist. Creating ${BE_TARGET_DIR}..."
                           sudo mkdir -p "${BE_TARGET_DIR}" || { echo "Failed to create ${BE_TARGET_DIR}"; exit 1; }
                         fi
-                        sudo chmod -R 775 "${BE_TARGET_DIR}" || { echo "Failed to set permissions for BE_TARGET_DIR"; exit 1; }
-                        sudo chown -R ubuntu:ubuntu "${BE_TARGET_DIR}" || { echo "Failed to change ownership of BE_TARGET_DIR"; exit 1; }
+                        
+                        USER="$(whoami)" 
+                        echo "Current user is $USER"
+                        sudo chown -R "$USER:$USER" "${BE_TARGET_DIR}" || { echo "Failed to change ownership of BE_TARGET_DIR"; exit 1; }
 
                         echo "Checking if service ${SERVICE} exists..."
                         if [ -f /etc/systemd/system/${SERVICE} ]; then
