modified backend 17:44

diff --git a/backend-pipeline.gocd.yaml b/backend-pipeline.gocd.yaml
--- a/backend-pipeline.gocd.yaml
+++ b/backend-pipeline.gocd.yaml
@@ -59,7 +59,7 @@ pipelines:
                         echo "Checking if BE_TARGET_DIR exists..."
                         if [ -d "${BE_TARGET_DIR}" ]; then
                           echo "BE_TARGET_DIR exists. moving all contents from BE_TARGET_DIR to BACKUP_DIR..."
-                          sudo mv ${BE_TARGET_DIR}/* "${BACKUP_DIR}" || { echo "Failed to move contents in ${BE_TARGET_DIR} to ${BACKUP_DIR}"; exit 1; }
+                          sudo mv ${BE_TARGET_DIR} "${BACKUP_DIR}" || { echo "Failed to move contents in ${BE_TARGET_DIR} to ${BACKUP_DIR}"; exit 1; }
                         else
                           echo "BE_TARGET_DIR does not exist. Creating ${BE_TARGET_DIR}..."
                           sudo mkdir -p "${BE_TARGET_DIR}" || { echo "Failed to create ${BE_TARGET_DIR}"; exit 1; }
