added permissions to target dir

diff --git a/backend-pipeline.gocd.yaml b/backend-pipeline.gocd.yaml
--- a/backend-pipeline.gocd.yaml
+++ b/backend-pipeline.gocd.yaml
@@ -101,6 +101,9 @@ pipelines:
                           echo "BE_TARGET_DIR exists. Using existing ${BE_TARGET_DIR}..."
                         fi
 
+                        echo "Changing permissions of BE_TARGET_DIR to ubuntu:ubuntu..."
+                        sudo chown -R ubuntu:ubuntu "${BE_TARGET_DIR}" || { echo "Failed to change permissions of BE_TARGET_DIR"; exit 1; }
+
                         echo "Copying and unzipping the backend artifacts to BE_TARGET_DIR..."
                         sudo cp "${BUILD_DIR}/backend.zip" "${BE_TARGET_DIR}/" || { echo "Failed to copy zip file"; exit 1; }
                         sudo unzip -o "${BE_TARGET_DIR}/backend.zip" -d "${BE_TARGET_DIR}" || { echo "Failed to unzip backend.zip"; exit 1; }
