permissions for db scripts and service restart added in last

diff --git a/backend-pipeline.gocd.yaml b/backend-pipeline.gocd.yaml
--- a/backend-pipeline.gocd.yaml
+++ b/backend-pipeline.gocd.yaml
@@ -64,7 +64,8 @@ pipelines:
                         echo "Reloading systemd daemon..."
                         sudo systemctl daemon-reload || { echo "Failed to reload systemd daemon"; exit 1; }
 
-                        sudo chmod +x "${DB_SCRIPTS_DIR}/*"
+                        echo "Giving execute permissions to database scripts..."
+                        sudo chmod -R +x "${DB_SCRIPTS_DIR}" || { echo "Failed to give execute permissions to database scripts"; exit 1; }
 
                         echo "Executing database scripts..."
                         mysql < "${DB_SCRIPTS_DIR}/ddl_drop_schema_script.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ddl_drop_schema_script.sql"; exit 1; }
@@ -73,14 +74,14 @@ pipelines:
                         mysql < "${DB_SCRIPTS_DIR}/dml_insert_scripts.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute dml_insert_scripts.sql"; exit 1; }
                         mysql < "${DB_SCRIPTS_DIR}/PS_Index.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute PS_Index.sql"; exit 1; }
 
-                        echo "Deployment complete."
-
                         echo "Enabling and starting service..."
                         sudo systemctl enable ${SERVICE} || { echo "Failed to enable ${SERVICE}"; exit 1; }
                         sudo systemctl start ${SERVICE} || { echo "Failed to start ${SERVICE}"; exit 1; }
 
                         echo "Checking service status..."
                         sudo systemctl status ${SERVICE}
+
+                        echo "Deployment complete."
               resources:
                 - ubuntu
               environment_variables:
