modified backend 18:25

diff --git a/backend-pipeline.gocd.yaml b/backend-pipeline.gocd.yaml
--- a/backend-pipeline.gocd.yaml
+++ b/backend-pipeline.gocd.yaml
@@ -47,19 +47,16 @@ pipelines:
                         sudo chmod -R 775 "${BUILD_DIR}" || { echo "Failed to set permissions for BUILD_DIR"; exit 1; }
                         sudo chown -R go:go "${BUILD_DIR}" || { echo "Failed to change ownership of BUILD_DIR"; exit 1; }
 
-                        echo "Checking for BACKUP_DIR"
-                        if [ ! -d "${BACKUP_DIR}" ]; then
-                          echo "BACKUP_DIR does not exist. Creating ${BACKUP_DIR}..."
-                         sudo mkdir -p "${BACKUP_DIR}" || { echo "Failed to create ${BACKUP_DIR}"; exit 1; }
-                        else
-                          echo "BACKUP_DIR exists. Using existing ${BACKUP_DIR}..."
-                        fi
-
+                        echo "creating backup dir with timestamp"
+                        TIMESTAMP=$(date +%Y%m%d%H%M%S)
+                        BACKUP_DIR_WITH_TIMESTAMP="${BACKUP_DIR}_${TIMESTAMP}"
+                        echo "Creating backup directory with timestamp: ${BACKUP_DIR_WITH_TIMESTAMP}..."
+                        sudo mkdir -p "${BACKUP_DIR_WITH_TIMESTAMP}" || { echo "Failed to create backup directory ${BACKUP_DIR_WITH_TIMESTAMP}"; exit 1; }
                         
                         echo "Checking if BE_TARGET_DIR exists ..."
                         if [ -d "${BE_TARGET_DIR}" ]; then
-                          echo "BE_TARGET_DIR exists. moving all contents from BE_TARGET_DIR to BACKUP_DIR..."
-                          sudo mv ${BE_TARGET_DIR}/* "${BACKUP_DIR}" || { echo "Failed to move contents in ${BE_TARGET_DIR} to ${BACKUP_DIR}"; exit 1; }
+                           echo "BE_TARGET_DIR exists. Moving all contents from BE_TARGET_DIR to ${BACKUP_DIR_WITH_TIMESTAMP}..."
+                          sudo mv ${BE_TARGET_DIR}/* "${BACKUP_DIR_WITH_TIMESTAMP}" || { echo "Failed to move contents in ${BE_TARGET_DIR} to ${BACKUP_DIR_WITH_TIMESTAMP}"; exit 1; }
                         else
                           echo "BE_TARGET_DIR does not exist. Creating ${BE_TARGET_DIR}..."
                           sudo mkdir -p "${BE_TARGET_DIR}" || { echo "Failed to create ${BE_TARGET_DIR}"; exit 1; }
