modified backend 21:09

diff --git a/backend-pipeline.gocd.yaml b/backend-pipeline.gocd.yaml
--- a/backend-pipeline.gocd.yaml
+++ b/backend-pipeline.gocd.yaml
@@ -67,35 +67,22 @@ pipelines:
                         echo "Checking for existing ps_be_*.zip files in BUILD_DIR..."
                         if ls "${BUILD_DIR}/ps_be_*.zip" > /dev/null 2>&1; then
                           echo "Found existing ps_be_*.zip files:"
-                          ls -l ${BUILD_DIR}/ps_be_*.zip
-                          echo "Removing existing zip files..."
-                          sudo rm -f ${BUILD_DIR}/ps_be_*.zip || { echo "Failed to remove existing zip files"; exit 1; }
+                          ls "${BUILD_DIR}/ps_be_*.zip"
+                          echo "Removing existing ps_be_*.zip files..."
+                          sudo rm -f "${BUILD_DIR}/ps_be_*.zip" || { echo "Failed to remove existing zip files"; exit 1; }
                         else
-                          echo "No existing ps_be_*.zip files found in BUILD_DIR. Proceeding..."
+                          echo "No existing ps_be_*.zip files found. Proceeding..."
                         fi
 
                         echo "Accessing SFTP machine to fetch the latest backend zip file..."
-                        latest_file=$(sudo -u go sftp -o StrictHostKeyChecking=no -i ${SFTP_KEY} ${SFTP_USER}@${SFTP_HOST} <<EOF
+                        sudo -u go sftp -o StrictHostKeyChecking=no -i /var/go/.ssh/id_rsa ${SFTP_USER}@${SFTP_HOST} <<EOF
                         cd ${SFTP_UPLOADS_DIR}
-                        ls -t ps_be_*.zip | head -n 1
+                        get \$(ls -t ps_be_*.zip | head -1) ${BUILD_DIR}/
                         bye
                         EOF
-                        )
-
-                        if [ -z "${latest_file}" ]; then
-                          echo "No ps_be_*.zip files found on SFTP server."
+                        if [ $? -ne 0 ]; then
+                          echo "Failed to fetch backend.zip from SFTP."
                           exit 1
-                        else
-                          echo "Fetching the latest file ${latest_file} from SFTP..."
-                          sudo -u go sftp -o StrictHostKeyChecking=no -i ${SFTP_KEY} ${SFTP_USER}@${SFTP_HOST} <<EOF
-                          cd ${SFTP_UPLOADS_DIR}
-                          get ${latest_file} ${BUILD_DIR}/
-                          bye
-                          EOF
-                          if [ $? -ne 0 ]; then
-                            echo "Failed to fetch ${latest_file} from SFTP."
-                            exit 1
-                          fi
                         fi
 
                         echo "Checking and creating BE_TARGET_DIR if needed..."
