modified backend 12:31

diff --git a/DB.gocd.yaml b/DB.gocd.yaml
--- a/DB.gocd.yaml
+++ b/DB.gocd.yaml
@@ -55,7 +55,7 @@ pipelines:
                           sudo mkdir -p "${DB_DIR}" || { echo "Failed to create ${DB_DIR}"; exit 1; }
                         fi
                         
-                        sudo chown -R go:go "${DB_DIR}"
+                        sudo chown -R ubuntu:ubuntu "${DB_DIR}"
 
                         echo "Fetching the specified database build file from SFTP..."
                         sudo -u go sftp -o StrictHostKeyChecking=no -i ${SFTP_KEY} ${SFTP_USER}@${SFTP_HOST} <<EOF
@@ -70,6 +70,12 @@ pipelines:
 
                         echo "Extracting database scripts into DB_DIR..."
                         sudo unzip -o "${DB_DIR}/${BUILD_FILE}" -d "${DB_DIR}" || { echo "Failed to extract database scripts"; exit 1; }
+
+                        echo "Setting ownership and permissions for files in DB_DIR..."
+                        sudo chown -R ubuntu:ubuntu "${DB_DIR}" || { echo "Failed to change ownership of files in BE_TARGET_DIR"; exit 1; }
+                        sudo chmod 644 "${DB_DIR}"/*.properties "${DB_DIR}"/*.jar "${DB_DIR}"/*.sh || { echo "Failed to set permissions for files"; exit 1; }
+                        sudo chmod 755 "${DB_DIR}/wrapper.sh" || { echo "Failed to set executable permission for wrapper.sh"; exit 1; }
+                        sudo chmod 755 "${DB_DIR}" || { echo "Failed to set permissions for DB_DIR"; exit 1; }
 
                         echo "Setting execute permissions for database scripts..."
                         sudo chmod -R +x "${DB_DIR}" || { echo "Failed to set permissions"; exit 1; }
@@ -92,7 +98,7 @@ pipelines:
                         echo "Starting service..."
                         sudo systemctl start ${SERVICE} || { echo "Failed to start ${SERVICE}"; exit 1; }
                         sudo systemctl status ${SERVICE}
-
+                        
               resources:
                 - ubuntu
               environment_variables:
