modified backend 12:42

diff --git a/DB.gocd.yaml b/DB.gocd.yaml
--- a/DB.gocd.yaml
+++ b/DB.gocd.yaml
@@ -71,11 +71,6 @@ pipelines:
                         echo "Extracting database scripts into DB_DIR..."
                         sudo unzip -o "${DB_DIR}/${BUILD_FILE}" -d "${DB_DIR}" || { echo "Failed to extract database scripts"; exit 1; }
 
-                        echo "Setting ownership and permissions for files in DB_DIR..."
-                        sudo chown -R ubuntu:ubuntu "${DB_DIR}" || { echo "Failed to change ownership of files in BE_TARGET_DIR"; exit 1; }
-                        sudo chmod 644 "${DB_DIR}"/*.properties "${DB_DIR}"/*.jar "${DB_DIR}"/*.sh || { echo "Failed to set permissions for files"; exit 1; }
-                        sudo chmod 755 "${DB_DIR}/wrapper.sh" || { echo "Failed to set executable permission for wrapper.sh"; exit 1; }
-                        sudo chmod 755 "${DB_DIR}" || { echo "Failed to set permissions for DB_DIR"; exit 1; }
 
                         echo "Setting execute permissions for database scripts..."
                         sudo chmod -R +x "${DB_DIR}" || { echo "Failed to set permissions"; exit 1; }
@@ -94,6 +89,12 @@ pipelines:
                         mysql < "${DB_DIR}/database-scripts/dml_insert_scripts.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute dml_insert_scripts.sql"; exit 1; }
                         mysql < "${DB_DIR}/database-scripts/ps_index_create.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ps_index_create.sql"; exit 1; }
                         echo "Database setup complete."
+
+                          echo "Setting ownership and permissions for files in DB_DIR..."
+                        sudo chown -R ubuntu:ubuntu "${DB_DIR}" || { echo "Failed to change ownership of files in BE_TARGET_DIR"; exit 1; }
+                        sudo chmod 644 "${DB_DIR}"/*.properties "${DB_DIR}"/*.jar "${DB_DIR}"/*.sh || { echo "Failed to set permissions for files"; exit 1; }
+                        sudo chmod 755 "${DB_DIR}/wrapper.sh" || { echo "Failed to set executable permission for wrapper.sh"; exit 1; }
+                        sudo chmod 755 "${DB_DIR}" || { echo "Failed to set permissions for DB_DIR"; exit 1; }
 
                         echo "Starting service..."
                         sudo systemctl start ${SERVICE} || { echo "Failed to start ${SERVICE}"; exit 1; }
