modified backend 14:40

diff --git a/DB.gocd.yaml b/DB.gocd.yaml
--- a/DB.gocd.yaml
+++ b/DB.gocd.yaml
@@ -33,7 +33,7 @@ pipelines:
                         export SFTP_USER=surya
                         export SFTP_KEY=/var/go/.ssh/id_rsa
                         export SFTP_UPLOADS_DIR=uploads
-                        export BUILD_FILE="ps_be_1.1.26_iifl_1.1.13-5763ce9-791.zip"
+                        export BUILD_FILE="ps_be_1.1.26_idfc_1.1.13-9f56559-321.zip"
                         export DB_USER=psdbadmin
                         export SERVICE=PrimeSquare.service
 
@@ -84,7 +84,7 @@ pipelines:
 
                         echo "Dropping and recreating the database..."
                         mysql < "${DB_DIR}/database-scripts/ddl_drop_schema_script.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ddl_drop_schema_script.sql"; exit 1; }
-                        mysql < "${DB_DIR}/database-scripts/iifl_primesquare_workflow_ddl_dml.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute primesquare_workflow_ddl_dml.sql"; exit 1; }
+                        mysql < "${DB_DIR}/database-scripts/idfc_primesquare_workflow_ddl_dml.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute primesquare_workflow_ddl_dml.sql"; exit 1; }
                         mysql < "${DB_DIR}/database-scripts/ddl_create_scripts.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ddl_create_scripts.sql"; exit 1; }
                         mysql < "${DB_DIR}/database-scripts/dml_insert_scripts.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute dml_insert_scripts.sql"; exit 1; }
                         mysql < "${DB_DIR}/database-scripts/ps_index_create.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ps_index_create.sql"; exit 1; }
diff --git a/front-end.gocd.yaml b/front-end.gocd.yaml
--- a/front-end.gocd.yaml
+++ b/front-end.gocd.yaml
@@ -35,7 +35,7 @@ pipelines:
                         export SFTP_USER=surya
                         export SFTP_KEY=/var/go/.ssh/id_rsa
                         export SFTP_UPLOADS_DIR=uploads
-                        export BUILD_FILE="ps_ui_1.1.26_iifl_1.1.13-a673bdf-607.zip"
+                        export BUILD_FILE="ps_ui_1.1.26_idfc_1.1.13-a64f5c1-346.zip"
                         export TARGET_HOST=172.16.7.109
 
                         echo "Creating UI_ARCHIVE directory if it doesn't exist..."
@@ -76,7 +76,7 @@ pipelines:
 
                         echo "Updating target host in configuration files..."
                         echo "Exporting TARGET_HOST: $TARGET_HOST"
-                        sudo sed -i "s|https://ps-targethost:3804|http://$TARGET_HOST|g" "${UI_TARGET_DIR}/prime-square/main.aef3be31078a3983.js " || { echo "Failed to update main.js"; exit 1; }
+                        sudo sed -i "s|https://ps-targethost:3804|http://$TARGET_HOST|g" "${UI_TARGET_DIR}/prime-square/main.*.js " || { echo "Failed to update main.js"; exit 1; }
 
                         sudo sed -i "s|https://ps-targethost:3804|http://$TARGET_HOST|g" "${UI_TARGET_DIR}/prime-square/assets/environment/environment.json" || { echo "Failed to update environment.json"; exit 1; }
 
