modified 18:18

diff --git a/DB.gocd.yaml b/DB.gocd.yaml
--- a/DB.gocd.yaml
+++ b/DB.gocd.yaml
@@ -36,11 +36,25 @@ pipelines:
                         export BUILD_FILE="ps_be_1.1.26_idfc_1.1.13-9f56559-321.zip"
                         export DB_USER=psdbadmin
 
+                         echo "Checking if service ${SERVICE} exists..."
+                        if [ -f /etc/systemd/system/${SERVICE} ]; then
+                          echo "${SERVICE} exists. Checking service status..."
+                          sudo systemctl status ${SERVICE} > /dev/null 2>&1
+                          if [ $? -eq 0 ]; then
+                            echo "${SERVICE} is running. Stopping the service..."
+                            sudo systemctl stop ${SERVICE} || { echo "Failed to stop ${SERVICE}"; exit 1; }
+                          else
+                            echo "${SERVICE} is not running."
+                          fi
+                        else
+                          echo "${SERVICE} does not exist. Proceeding..."
+                        fi
+
                         echo "Creating and setting up DB_DIR..."
                         if [ ! -d "${DB_DIR}" ]; then
                           sudo mkdir -p "${DB_DIR}" || { echo "Failed to create ${DB_DIR}"; exit 1; }
                         fi
-                        sudo chmod -R 755 "${DB_DIR}"
+                        
                         sudo chown -R ubuntu:ubuntu "${DB_DIR}"
 
                         echo "Fetching the specified database build file from SFTP..."
@@ -74,6 +88,11 @@ pipelines:
                         mysql < "${DB_DIR}/database-scripts/dml_insert_scripts.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute dml_insert_scripts.sql"; exit 1; }
                         mysql < "${DB_DIR}/database-scripts/ps_index_create.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ps_index_create.sql"; exit 1; }
                         echo "Database setup complete."
+
+                        echo "Starting service..."
+                        sudo systemctl start ${SERVICE} || { echo "Failed to start ${SERVICE}"; exit 1; }
+                        sudo systemctl status ${SERVICE}
+                        
               resources:
                 - ubuntu
               environment_variables:
diff --git a/backend-pipeline.gocd.yaml b/backend-pipeline.gocd.yaml
--- a/backend-pipeline.gocd.yaml
+++ b/backend-pipeline.gocd.yaml
@@ -51,7 +51,8 @@ pipelines:
 
                         USER="$(whoami)" 
                         echo "Current user is $USER"
-                        sudo chown -R "$USER:$USER" "${BUILD_DIR}" || { echo "Failed to change ownership of BUILD_DIR"; exit 1; }
+                        echo "changing permissions to ubuntu:ubuntu"
+                        sudo chown -R ubuntu:ubuntu "${BUILD_DIR}" || { echo "Failed to change ownership of BUILD_DIR"; exit 1; }
 
                         echo "Checking if BE_TARGET_DIR exists..."
                         if [ -d "${BE_TARGET_DIR}" ]; then
@@ -64,7 +65,9 @@ pipelines:
                         
                         USER="$(whoami)" 
                         echo "Current user is $USER"
-                        sudo chown -R "$USER:$USER" "${BE_TARGET_DIR}" || { echo "Failed to change ownership of BE_TARGET_DIR"; exit 1; }
+                         echo "changing permissions to ubuntu:ubuntu"
+                        sudo chown -R ubuntu:ubuntu "${BE_TARGET_DIR}" || { echo "Failed to change ownership of BE_TARGET_DIR"; exit 1; }
+                  
 
                         echo "Checking if service ${SERVICE} exists..."
                         if [ -f /etc/systemd/system/${SERVICE} ]; then
@@ -111,9 +114,6 @@ pipelines:
 
                         echo "Reloading systemd daemon..."
                         sudo systemctl daemon-reload || { echo "Failed to reload systemd daemon"; exit 1; }
-
-                        echo "Giving execute permissions to database scripts..."
-                        sudo chmod -R +x "${DB_SCRIPTS_DIR}" || { echo "Failed to give execute permissions to database scripts"; exit 1; }
 
                         echo "Starting service..."
                         sudo systemctl start ${SERVICE} || { echo "Failed to start ${SERVICE}"; exit 1; }
diff --git a/front-end.gocd.yaml b/front-end.gocd.yaml
--- a/front-end.gocd.yaml
+++ b/front-end.gocd.yaml
@@ -45,7 +45,6 @@ pipelines:
                           echo "UI_ARCHIVE directory already exists."
                         fi
 
-                        sudo chmod -R 775 "${UI_ARCHIVE}" || { echo "Failed to set permissions for UI_ARCHIVE"; exit 1; }
                         sudo chown -R ubuntu:ubuntu "${UI_ARCHIVE}" || { echo "Failed to set ownership for UI_ARCHIVE"; exit 1; }
 
                         echo "Fetching UI build from SFTP server..."
@@ -71,14 +70,15 @@ pipelines:
                         echo "Unzipping UI build to UI_TARGET_DIR..."
                         sudo unzip -o "${UI_ARCHIVE}/${BUILD_FILE}" -d "${UI_TARGET_DIR}" || { echo "Failed to unzip UI build"; exit 1; }
 
-                        echo "permissions for environment.json"
-                        sudo chown ubuntu:ubuntu /var/www/html/prime-square/assets/environment/environment.json
-                        sudo chmod 664 /var/www/html/prime-square/assets/environment/environment.json
+
+                        echo "permissions for UI_TARGET_DIR/prime-square"
+                        sudo chown -R root:root UI_TARGET_DIR/prime-square
 
                         echo "Updating target host in configuration files..."
                         echo "Exporting TARGET_HOST: $TARGET_HOST"
-                        sudo sed -i "s|https://ps-targethost:3804/prime-square|http://$TARGET_HOST/prime-square|g" "${UI_TARGET_DIR}/prime-square/main.e1f206db06620922.js" || { echo "Failed to update main.js"; exit 1; }
-                        sudo sed -i "s|https://ps-targethost:3804/prime-square|http://$TARGET_HOST/prime-square|g" "${UI_TARGET_DIR}/prime-square/assets/environment/environment.json" || { echo "Failed to update environment.json"; exit 1; }
+                        sudo sed -i "s|https://ps-targethost:3804|http://$TARGET_HOST|g" "${UI_TARGET_DIR}/prime-square/main.e1f206db06620922.js" || { echo "Failed to update main.js"; exit 1; }
+
+                        sudo sed -i "s|https://ps-targethost:3804|http://$TARGET_HOST|g" "${UI_TARGET_DIR}/prime-square/assets/environment/environment.json" || { echo "Failed to update environment.json"; exit 1; }
 
                         echo "Starting Apache2 service..."
                         sudo systemctl start apache2 || { echo "Failed to start Apache2"; exit 1; }
diff --git a/replacing-jar.gocd.yaml b/replacing-jar.gocd.yaml
--- a/replacing-jar.gocd.yaml
+++ b/replacing-jar.gocd.yaml
@@ -97,21 +97,18 @@ pipelines:
                           echo "BACKUP_DIR exists. Using existing ${BACKUP_DIR}..."
                         fi
 
-                        echo "Checking for backend (ps_be)..."
-                        BE_ZIP="${BUILD_DIR}/${BUILD_FILE}"
-                        if [ -z "${BE_ZIP}" ]; then
-                          echo "Specified build file (${BUILD_FILE}) not found in ${BUILD_DIR}!"
-                          exit 1
-                        else
-                          echo "Found backend zip: ${BE_ZIP}"
+                        
                           echo "Unzipping backend.zip..."
-                          sudo unzip -o "${BE_ZIP}" -d "${BE_ARCHIVE_DIR}" || { echo "Failed to unzip ps_be"; exit 1; }
+                          sudo unzip -o "${BUILD_DIR}/${BUILD_FILE}" -d "${BE_ARCHIVE_DIR}" || { echo "Failed to unzip ps_be"; exit 1; }
 
                           JAR_FILE=$(find "${BE_ARCHIVE_DIR}" -type f -name "core-*.jar" | head -n 1)
                           if [ -z "${JAR_FILE}" ]; then
                             echo "No core-*.jar file found in the ps_be zip!"
                             exit 1
                           fi
+
+                          echo "giving permissions for jar"
+                          sudo chown ubuntu:ubuntu #JAR_FILE
 
                           echo "Checking for BE_TARGET_DIR"
                           if [ ! -d "${BE_TARGET_DIR}" ]; then
