modified backend 1:03

diff --git a/front-end.gocd.yaml b/front-end.gocd.yaml
--- a/front-end.gocd.yaml
+++ b/front-end.gocd.yaml
@@ -77,8 +77,8 @@ pipelines:
 
                         echo "Updating target host in configuration files..."
                         echo "Exporting TARGET_HOST: $TARGET_HOST"
-                        sudo sed -i 's|https://ps-targethost:3804/prime-square|http://$TARGET_HOST/prime-square|g' "${UI_TARGET_DIR}/prime-square/main.e1f206db06620922.js" || { echo "Failed to update main.js"; exit 1; }
-                        sudo sed -i 's|https://ps-targethost:3804/prime-square|http://$TARGET_HOST/prime-square|g' "${UI_TARGET_DIR}/prime-square/assets/environment/environment.json" || { echo "Failed to update environment.json"; exit 1; }
+                        sudo sed -i "s|https://ps-targethost:3804/prime-square|http://$TARGET_HOST/prime-square|g" "${UI_TARGET_DIR}/prime-square/main.e1f206db06620922.js" || { echo "Failed to update main.js"; exit 1; }
+                        sudo sed -i "s|https://ps-targethost:3804/prime-square|http://$TARGET_HOST/prime-square|g" "${UI_TARGET_DIR}/prime-square/assets/environment/environment.json" || { echo "Failed to update environment.json"; exit 1; }
 
                         echo "Starting Apache2 service..."
                         sudo systemctl start apache2 || { echo "Failed to start Apache2"; exit 1; }
