modified backend only 18:43

diff --git a/replacing-jar.gocd.yaml b/replacing-jar.gocd.yaml
--- a/replacing-jar.gocd.yaml
+++ b/replacing-jar.gocd.yaml
@@ -42,6 +42,8 @@ pipelines:
                         echo "creating BUILD_DIR and BACKUP_DIR"
                         mkdir -p "${BUILD_DIR}"
                         mkdir -p "${BACKUP_DIR}"
+                        sudo chown -R ubuntu:ubuntu "${BUILD_DIR}" || { echo "Failed to change ownership of BUILD_DIR"; exit 1; }
+                        sudo chown -R ubuntu:ubuntu "${BACKUP_DIR}" || { echo "Failed to change ownership of BACKUP_DIR"; exit 1; }
 
                         echo "Remove old backend zip files"
                         sudo rm -f "${BUILD_DIR}/ps_be_*.zip"
