modified backend only 16:00

diff --git a/replacing-jar.gocd.yaml b/replacing-jar.gocd.yaml
--- a/replacing-jar.gocd.yaml
+++ b/replacing-jar.gocd.yaml
@@ -33,30 +33,15 @@ pipelines:
                         export BE_TARGET_DIR=/home/ubuntu/prime-square
                         export BE_ARCHIVE_DIR=/home/ubuntu/archive/
                         export SERVICE=PrimeSquare.service
-                        export DB_SCRIPTS_DIR=/home/ubuntu/prime-square/database-scripts
-                        export DB_USER=psdbadmin
-                        export DB_PASS=6%EOm@Te1sb19Th6
                         export SFTP_HOST=172.16.7.116
                         export SFTP_USER=surya
                         export SFTP_KEY=/var/go/.ssh/id_rsa
                         export SFTP_UPLOADS_DIR=uploads
-
-                        echo "Checking and creating BUILD_DIR if needed..."
-                        if [ ! -d "${BUILD_DIR}" ]; then
-                          echo "BUILD_DIR does not exist. Creating ${BUILD_DIR}..."
-                          mkdir -p "${BUILD_DIR}" || { echo "Failed to create ${BUILD_DIR}"; exit 1; }
-                        else
-                          echo "BUILD_DIR exists. Using existing ${BUILD_DIR}..."
-                        fi
-
+                        
+                        echo "creating BUILD_DIR if needed..."
+                        mkdir -p "${BUILD_DIR}"
                         echo "Checking for existing backend files in BUILD_DIR..."
-                        if ls "${BUILD_DIR}/ps_be_*.zip" > /dev/null 2>&1; then
-                          echo "Found existing ps_be_*.zip files. Removing them..."
-                          sudo rm -f "${BUILD_DIR}/ps_be_*.zip" || { echo "Failed to remove existing zip files"; exit 1; }
-                        else
-                          echo "No existing ps_be_*.zip files found. Proceeding..."
-                        fi
-
+                        sudo rm -f "${BUILD_DIR}/ps_be_*.zip"
                         echo "Accessing SFTP machine to fetch the backend zip file..."
                         sftp -o StrictHostKeyChecking=no -i "${SFTP_KEY}" "${SFTP_USER}@${SFTP_HOST}" <<EOF
                         cd ${SFTP_UPLOADS_DIR}
@@ -65,83 +50,57 @@ pipelines:
                         EOF
 
                         if [ $? -ne 0 ]; then
-                          echo "Failed to fetch backend.zip from SFTP."
+                          echo "Failed to fetch backend zip file from SFTP."
                           exit 1
                         fi
 
-                        echo "Checking if service ${SERVICE} exists..."
-                        if [ -f /etc/systemd/system/${SERVICE} ]; then
-                          echo "${SERVICE} exists. Checking service status..."
-                          if systemctl is-active --quiet ${SERVICE}; then
-                            echo "${SERVICE} is running. Stopping the service..."
-                            sudo systemctl stop ${SERVICE} || { echo "Failed to stop ${SERVICE}"; exit 1; }
-                          else
-                            echo "${SERVICE} is not running."
-                          fi
-                        else
-                          echo "${SERVICE} does not exist. Proceeding..."
+                        if systemctl is-active --quiet ${SERVICE}; then
+                          sudo systemctl stop ${SERVICE}
                         fi
 
-                        echo "Checking for BE_ARCHIVE_DIR"
-                        if [ ! -d "${BE_ARCHIVE_DIR}" ]; then
-                          echo "BE_ARCHIVE_DIR does not exist. Creating ${BE_ARCHIVE_DIR}..."
-                          mkdir -p "${BE_ARCHIVE_DIR}" || { echo "Failed to create ${BE_ARCHIVE_DIR}"; exit 1; }
-                        else
-                          echo "BE_ARCHIVE_DIR exists. Using existing ${BE_ARCHIVE_DIR}..."
-                        fi
+                        echo "Creating BE_ARCHIVE_DIR"
+                        mkdir -p "${BE_ARCHIVE_DIR}"
 
                         echo "Checking for backend (ps_be)..."
                         BE_ZIP=$(ls ${BUILD_DIR}/ps_be*.zip 2>/dev/null | head -n 1)
                         if [ -z "${BE_ZIP}" ]; then
                           echo "No ps_be zip file found in ${BUILD_DIR}!"
                           exit 1
-                        else
-                          echo "Found backend zip: ${BE_ZIP}"
-                          echo "Unzipping backend.zip..."
-                          unzip -o "${BE_ZIP}" -d "${BE_ARCHIVE_DIR}" || { echo "Failed to unzip ps_be"; exit 1; }
-
-                          JAR_FILE=$(find "${BE_ARCHIVE_DIR}" -type f -name "core-*.jar" | head -n 1)
-                          if [ -z "${JAR_FILE}" ]; then
-                            echo "No core-*.jar file found in the ps_be zip!"
-                            exit 1
-                          fi
-
-                          echo "Checking for BE_TARGET_DIR..."
-                          if [ ! -d "${BE_TARGET_DIR}" ]; then
-                            echo "BE_TARGET_DIR does not exist. Creating ${BE_TARGET_DIR}..."
-                          fi
-
-                          if ls "${BE_TARGET_DIR}/core-*.jar" > /dev/null 2>&1; then
-                            echo "Archiving existing JAR file(s)..."
-                            sudo mv "${BE_TARGET_DIR}/core-*.jar" "${BE_ARCHIVE_DIR}/core-$(date +%F-%T).jar" || { echo "Failed to archive core JAR"; exit 1; }
-                          else
-                            echo "No existing core-*.jar file found to archive."
-                          fi
-
-                          echo "Copying new JAR file to BE_TARGET_DIR..."
-                          sudo cp "${JAR_FILE}" "${BE_TARGET_DIR}" || { echo "Failed to copy JAR file"; exit 1; }
-
-                          echo "Cleaning up BE_ARCHIVE_DIR..."
-                          rm -rf "${BE_ARCHIVE_DIR}" || { echo "Failed to clean up BE_ARCHIVE_DIR"; exit 1; }
                         fi
+
+                        echo "Unzip BE_ZIP to BE_ARCHIVE_DIR..."
+                        unzip -o "${BE_ZIP}" -d "${BE_ARCHIVE_DIR}"
+
+                        echo "Checking for JAR file..."
+                        JAR_FILE=$(find "${BE_ARCHIVE_DIR}" -type f -name "core-*.jar" | head -n 1)
+                        if [ -z "${JAR_FILE}" ]; then
+                          echo "No core-*.jar file found in the archive!"
+                          exit 1
+                        fi
+
+                        echo "Archiving existing JAR file(s)..."
+                        if ls "${BE_TARGET_DIR}/core-*.jar" > /dev/null 2>&1; then
+                          sudo mv "${BE_TARGET_DIR}/core-*.jar" "${BE_ARCHIVE_DIR}/core-$(date +%F-%T).jar"
+                        fi
+
+                        echo "Copying new JAR file to BE_TARGET_DIR..."
+                        sudo cp "${JAR_FILE}" "${BE_TARGET_DIR}"
+
+                        echo "Cleaning up BE_ARCHIVE_DIR..."
+                        rm -rf "${BE_ARCHIVE_DIR}"\
 
                         echo "Listing files in BE_TARGET_DIR..."
                         ls -l "${BE_TARGET_DIR}"
 
                         echo "Checking and copying service file if needed..."
                         if [ ! -f /etc/systemd/system/${SERVICE} ]; then
-                          sudo cp "${BE_TARGET_DIR}/service/${SERVICE}" /etc/systemd/system/ || { echo "Failed to copy service file"; exit 1; }
-                          echo "Enabling the service..."
-                          sudo systemctl enable ${SERVICE} || { echo "Failed to enable ${SERVICE}"; exit 1; }
-                        else
-                          echo "Service file already exists. Skipping copy."
+                          sudo cp "${BE_TARGET_DIR}/service/${SERVICE}" /etc/systemd/system/
+                          sudo systemctl enable ${SERVICE}
                         fi
-
-                        echo "Reloading systemd daemon..."
-                        sudo systemctl daemon-reload || { echo "Failed to reload systemd daemon"; exit 1; }
-
-                        echo "Deployment complete. Starting the service..."
-                        sudo systemctl start ${SERVICE} || { echo "Failed to start ${SERVICE}"; exit 1; }
+                        
+                        echo "Jar replaced successfully . Starting the service..."
+                        sudo systemctl daemon-reload
+                        sudo systemctl start ${SERVICE}
                         sudo systemctl status ${SERVICE}
 
 environments:
