modified replace jar only 10:51

diff --git a/replacing-jar.gocd.yaml b/replacing-jar.gocd.yaml
--- a/replacing-jar.gocd.yaml
+++ b/replacing-jar.gocd.yaml
@@ -116,15 +116,15 @@ pipelines:
                           fi
 
                           echo "Checking for BE_TARGET_DIR"
-                        if [ ! -d "${BE_TARGET_DIR}" ]; then
-                          echo "BE_TARGET_DIR does not exist.
-                        else
-                          echo "BE_TARGET_DIR exists."
-                        fi
+                          if [ ! -d "${BE_TARGET_DIR}" ]; then
+                            echo "BE_TARGET_DIR does not exist.
+                          else
+                            echo "BE_TARGET_DIR exists."
+                          fi
 
                           if ls "${BE_TARGET_DIR}/core-*.jar" > /dev/null 2>&1; then
                             echo "Archiving existing JAR file(s)..."
-                            sudo mv "${BE_TARGET_DIR}/*" "${BACKUP_DIR}/" || { echo "Failed to archive core JAR"; exit 1; }
+                            sudo mv "${BE_TARGET_DIR}"/* "${BACKUP_DIR}/" || { echo "Failed to archive core JAR"; exit 1; }
                           else
                             echo "No existing core-*.jar file found to archive."
                           fi
@@ -151,10 +151,9 @@ pipelines:
                         echo "Reloading systemd daemon..."
                         sudo systemctl daemon-reload || { echo "Failed to reload systemd daemon"; exit 1; }
 
-                        echo "jar replaced successfully . Starting the service..."
+                        echo "JAR replaced successfully. Starting the service..."
                         sudo systemctl start ${SERVICE} || { echo "Failed to start ${SERVICE}"; exit 1; }
                         sudo systemctl status ${SERVICE}
-
 environments:
   Frontandbackend:
     pipelines:
