modified backend 18:29

diff --git a/replacing-jar.gocd.yaml b/replacing-jar.gocd.yaml
--- a/replacing-jar.gocd.yaml
+++ b/replacing-jar.gocd.yaml
@@ -146,7 +146,7 @@ pipelines:
                           echo "Copying new JAR file to BE_TARGET_DIR..."
                           sudo cp "${JAR_FILE}" "${BE_TARGET_DIR}" || { echo "Failed to copy JAR file"; exit 1; }
                           echo "Setting ownership and permissions for files in BE_TARGET_DIR..."
-                        sudo chown -R ubuntu:ubuntu "${BE_TARGET_DIR}" || { echo "Failed to change ownership of files in BE_TARGET_DIR"; exit 1; }
+                        sudo chown -R ubuntu:ubuntu "${JAR_FILE}" || { echo "Failed to change ownership of files in BE_TARGET_DIR"; exit 1; }
 
                           echo "Cleaning up BE_ARCHIVE_DIR..."
                           sudo rm -rf "${BE_ARCHIVE_DIR}" || { echo "Failed to clean up BE_ARCHIVE_DIR"; exit 1; }
