modified backend only 14:23

diff --git a/replacing-jar.gocd.yaml b/replacing-jar.gocd.yaml
--- a/replacing-jar.gocd.yaml
+++ b/replacing-jar.gocd.yaml
@@ -113,7 +113,13 @@ pipelines:
                             echo "BE_TARGET_DIR does not exist"
                           else
                             echo "BE_TARGET_DIR exists. Using ${BE_TARGET_DIR}..."
-                            sudo mv /home/ubuntu/prime-square/core-*.jar /home/ubuntu/archive/core-$(date +%F-%T).jar || { echo "Failed to archive core JAR"; exit 1; }
+                            if ls /home/ubuntu/prime-square/core-*.jar 1> /dev/null 2>&1; then
+                            echo "JAR file(s) found. Archiving existing JAR file(s)..."
+                            sudo mv /home/ubuntu/prime-square/core-*.jar /home/ubuntu/archive/core-$(date +%F-%T).jar || {echo "Failed to archive core JAR"; exit 1; }
+                          else
+                            echo "No JAR file found to archive."
+                          fi
+                          
                             cp "${JAR_FILE}" "${BE_TARGET_DIR}" || { echo "Failed to copy JAR file"; exit 1; }
                             rm -rf "${BE_ARCHIVE_DIR}" || { echo "Failed to clean up BE_ARCHIVE_DIR"; exit 1; }
                           fi 
